**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [1]:
#Code here
import numpy as np

x=np.zeros(10)
x[4]=5
print(x)



[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [2]:
#Code here
#` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

import numpy as np

a = int(input("Enter a: "))
b = int(input("Enter b: "))

arr = np.random.rand(a, b)
print(arr)
print(np.average(arr))

#` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

[[0.31646886 0.99409585 0.24204938]
 [0.41848622 0.51836254 0.69608929]]
0.5309253565084692


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
#Code here
import numpy as np

a=int(input("Enter the number of rows: "))
b=int(input("Enter the number of columns: "))
s= np.ones((a,b))
s[1:-1,1:-1]=0
print(s)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [6]:
#Code here
import numpy as np

np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [7]:
#Code here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:

#Code here

import numpy as np

z=np.zeros((5,5))

z+=np.arange(5)

print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [18]:
#code here
z=np.random.randint(0,100,(10,2))
print(z)
point = np.array([2,3])
(np.sqrt(np.sum(((z-point)**2),axis=1))).astype(int)


[[29 35]
 [11 86]
 [45 50]
 [ 2 59]
 [40 47]
 [79 84]
 [69 62]
 [ 9 46]
 [18 90]
 [92 37]]


array([ 41,  83,  63,  56,  58, 111,  89,  43,  88,  96])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [2]:
#Code here
import numpy as np
np.unravel_index(100,(6,7,8))


(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [6]:
#Code here
INPUT=input()
a=INPUT.split()
a=np.array(a,dtype=float)
a= a[::-1]
print(a)



[9. 8. 7. 6. 5. 4. 3. 2. 1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [9]:
#Code here
import numpy as np

b=np.array([1,2,3,4,5,6,7,8,9,10])
a=b.size
print(a)


10


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [11]:
#Code here
def q(arr):
    if type(arr) is not np.ndarray:
        raise TypeError("Input must be a numpy array")
    s= np.sum((np.exp(arr)))
    return np.exp(arr)/s

q(np.array([[[86.03331084, 37.7285648 , 48.64908087, 87.16563062, 38.40852563 ,37.20006318]]]))

array([[[2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
         5.05514197e-22, 1.50974911e-22]]])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [15]:
#Coder here
def qq(*args):
    for i in args:
        if type(i) is not np.ndarray:
            raise TypeError("qq() only accepts numpy arrays")

    return np.vstack(args)

a= np.arange(10)
b= np.random.rand(10)*10
c= np.random.rand(10)*10

qq(a,b,c)



array([[0.        , 1.        , 2.        , 3.        , 4.        ,
        5.        , 6.        , 7.        , 8.        , 9.        ],
       [0.94308321, 0.21249723, 1.58230189, 2.90736129, 9.0210588 ,
        6.45666062, 6.39252781, 9.16399568, 0.567679  , 1.2438553 ],
       [6.26177059, 7.86710705, 0.14950068, 8.22105517, 9.64868306,
        8.38076612, 8.35588583, 8.51710394, 0.63270673, 7.38051524]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [19]:
#Code here
def a(start:str,end:str):
    if type(start)!=str and type(end)!=str:
        raise TypeError("Both start and end must be of type string")

    return np.arange(start,end,dtype="datetime64[D]")

b=a("2020-01-01","2020-01-31")
print(b)

['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12' '2020-01-13' '2020-01-14' '2020-01-15'
 '2020-01-16' '2020-01-17' '2020-01-18' '2020-01-19' '2020-01-20'
 '2020-01-21' '2020-01-22' '2020-01-23' '2020-01-24' '2020-01-25'
 '2020-01-26' '2020-01-27' '2020-01-28' '2020-01-29' '2020-01-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [26]:
#code here
a= np.arange(1,10).reshape(3,3)
print(a)
b= np.mean(a,axis=1,keepdims=True)
print(b)
print(a-b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [27]:
#Code here
import numpy as np

a= np.arange(1,10).reshape(3,3)
print(a)

a[:,[0,2,1]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 3, 2],
       [4, 6, 5],
       [7, 9, 8]])

###`Q-16:` Replace odd elements in arrays with -1.

In [36]:
#Code here
import numpy as np

a= np.arange(1,10).reshape(3,3)
a[a%2 !=0]=-1
print(a)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [38]:
#Code here
#Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

c=np.maximum(a,b)
print(c)



[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [42]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

v=arr1[:,::2]
v
xm=np.max(v)
xmin=np.min(v)
xn=(v-xmin)/(xm-xmin)
xn

array([[0.28285357, 0.12098456, 0.33354193],
       [0.68408427, 0.52596996, 0.41051314],
       [0.92000417, 1.        , 0.42459324],
       [0.27357113, 0.30851064, 0.31904464],
       [0.25761368, 0.91791823, 0.1093033 ],
       [0.8625365 , 0.96036713, 0.07071339],
       [0.64528577, 0.        , 0.91395494],
       [0.71224447, 0.47090113, 0.52920317]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [45]:
#Code here
def nthmax(arr, n):
    if n > len(arr):
        raise IndexError("n is greater than the length of the array")

    # Sort the array in descending order
    arr.sort()

    # Return the nth maximum value
    return arr[-n]

# Test the function
nthmax([12,34,40,7,1,0],3)



12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [51]:
#code here
a = np.array([1,2,3])
a=np.hstack([np.repeat(a,3),np.tile(a,3)])
print(a)
 


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
